test: testing ci

diff --git a/.github/workflows/approvepr.yml b/.github/workflows/approvepr.yml
--- a/.github/workflows/approvepr.yml
+++ b/.github/workflows/approvepr.yml
@@ -1,16 +1,42 @@
 name: Approve Pull Request
 on: 
-  workflow_dispatch
+  workflow_run:
+    workflows: [Create Pull Request]
+    types: [completed]
 
 permissions: write-all
   
 jobs:
-  githubactionsbot:
+  CI:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-      
+
+      - name: Run CI checks
+        id: ci
+        run: |
+          # Define a simple addition function
+          add() {
+            echo $(($1 + $2))
+          }
+
+          # Call the addition function with two numbers
+          result=$(add 5 3)
+
+          # Output the result of the addition
+          echo "Addition result: $result"
+
+          # Fail the CI job if the result is not equal to 8
+          if [[ $result -ne 8 ]]; then
+            echo "::error::Addition result is not equal to 8"
+            exit 1
+          fi
+
+  githubactionsbot:
+    runs-on: ubuntu-latest
+    needs: CI
+    steps:
       - name: Get Recent PR Number
         id: pr_number
         run: |
